name: 'Testes de Unidade'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 5'
  
jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando dependências
        run: npm install

      - name: Executando testes de unidade
        run: npm test
        
      - name: Salvando relatório de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./mochawesome-report
          name: Relatório de testes de unidade